### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Demonmegi** [Demonmegi/Eurale-United#1]
- [ ]  Build Citadel Avalon

- [ ]  Build Village 1-16

- [ ] Build Cave01, Cave02

- [ ]  Build Crypt01,02,03

- [ ]  Build Temple

- [ ]  Build Forest 1-9

- [ ]  Build the 3 Astralplane dimensions (Frosthelm, Infernus, Notsuoh)

- [ ] First List of Items

- [ ] First List of Enemies and Area by Level
