### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Demonmegi** [Demonmegi/Eurale-United#1]
- [x] Include every NPC in the existing Areass so far
- [ ] Finish cave02, temple and the crypts
- [ ] Start with Forest
- [ ] Place Enemies according to the Enemy level list
